<?php

return [
    'candy' => [
        'name' => 'Candy',
        'primary' => '#d96f9b',
        'secondary' => '#fce7f3',
        'background' => '#fff9f6',
        'text' => '#3b2630',
        'muted' => '#9b6b7e',
        'card' => '#fffefe',
        'border' => '#f2c9d8',
        'badge' => '#fde8f1',
        'badge_text' => '#9f4568',
    ],

    'lavender' => [
        'name' => 'Lavanda',
        'primary' => '#7c3aed',
        'secondary' => '#ede9fe',
        'background' => '#f8f5ff',
        'text' => '#211536',
        'muted' => '#75668f',
        'card' => '#fdfcff',
        'border' => '#d9ccfb',
        'badge' => '#eee9ff',
        'badge_text' => '#5b36b2',
    ],

    'emerald' => [
        'name' => 'Verde',
        'primary' => '#16a34a',
        'secondary' => '#dcfce7',
        'background' => '#f0fdf4',
        'text' => '#052e16',
        'muted' => '#4f725e',
        'card' => '#fbfffc',
        'border' => '#a7e8bd',
        'badge' => '#d9fbe5',
        'badge_text' => '#136337',
    ],

    'midnight' => [
        'name' => 'Midnight',
        'primary' => '#8b5cf6',
        'secondary' => '#312e81',
        'background' => '#0f172a',
        'text' => '#f8fafc',
        'muted' => '#a6b0c3',
        'card' => '#182238',
        'border' => '#3b4862',
        'badge' => '#2c276d',
        'badge_text' => '#e6ddff',
    ],

    'sunset' => [
        'name' => 'Sunset',
        'primary' => '#e11d48',
        'secondary' => '#fed7aa',
        'background' => '#fff7ed',
        'text' => '#431407',
        'muted' => '#9a5b3f',
        'card' => '#fffaf5',
        'border' => '#fdba74',
        'badge' => '#ffe4c7',
        'badge_text' => '#9a3412',
    ],

    'ocean' => [
        'name' => 'Ocean',
        'primary' => '#0284c7',
        'secondary' => '#bae6fd',
        'background' => '#f0f9ff',
        'text' => '#082f49',
        'muted' => '#486a80',
        'card' => '#fafdff',
        'border' => '#7dd3fc',
        'badge' => '#dbeafe',
        'badge_text' => '#075985',
    ],

    'mono' => [
        'name' => 'Mono',
        'primary' => '#111827',
        'secondary' => '#e5e7eb',
        'background' => '#f9fafb',
        'text' => '#111827',
        'muted' => '#6b7280',
        'card' => '#ffffff',
        'border' => '#d1d5db',
        'badge' => '#f3f4f6',
        'badge_text' => '#374151',
    ],

    'ruby' => [
        'name' => 'Ruby',
        'primary' => '#be123c',
        'secondary' => '#ffe4e6',
        'background' => '#fff1f2',
        'text' => '#3f101c',
        'muted' => '#8c5966',
        'card' => '#fffafa',
        'border' => '#fecdd3',
        'badge' => '#ffe4e6',
        'badge_text' => '#9f1239',
    ],
];
